blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/DataDog/pathfinding.cloud/discussions
    about: Ask questions or discuss ideas with the community
