name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: " # Prefix for the issue title
labels: [enhancement, "feature request"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out our feature request form!"
  - type: input
    id: feature-summary
    attributes:
      label: "Feature Summary"
      description: "A clear and concise summary of the feature."
      placeholder: "Add a summary of the feature here."
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Detailed description of the feature."
      placeholder: "Add a detailed description of the feature here."
    validations:
      required: true
  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Check all that apply."
      options:
        - label: "New functionality"
        - label: "Performance improvement"
        - label: "User interface enhancement"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature?"
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: markdown
    attributes:
      value: "Please ensure your request does not contain any sensitive information and is appropriate for a public repository."
