#!/usr/bin/env python3
"""
Generate per-lab static HTML stubs at docs/labs/{slug}/index.html.

Each stub mirrors docs/labs/index.html exactly except for the head fields
that drive social-media unfurls: <title>, <meta name="description">, and
the og:* / twitter:* meta tags. The body and script tags are unchanged so
the existing SPA boots and renders the lab detail view as usual.

Why stubs at all: social crawlers (Twitter, LinkedIn, Slack, Facebook,
iMessage) don't execute JavaScript. Meta tags must be in the served HTML.
With a stub per lab, GitHub Pages serves /labs/{slug}/index.html directly
and crawlers see the right tags. The SPA takes over for human visitors.

Per-lab hero images live at /images/labs/{slug}.png (generated by
scripts/generate-lab-hero-images.js). If a lab's PNG is missing, the stub
falls back to the generic /images/pathfinding-cloud-labs.png.

Usage:
    python scripts/generate-lab-stubs.py
"""

import json
import re
import sys
from html import escape
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
TEMPLATE_PATH = DOCS_DIR / "labs" / "index.html"
LABS_DATA_DIR = DOCS_DIR / "labs" / "data"
LABS_OUTPUT_DIR = DOCS_DIR / "labs"
LABS_INDEX_PATH = DOCS_DIR / "labs.json"

SITE_BASE_URL = "https://pathfinding.cloud"
GENERIC_HERO_URL = f"{SITE_BASE_URL}/images/pathfinding-cloud-labs.png"

# Marker injected into every generated stub. Reconciliation only removes
# stub dirs whose index.html carries this marker, so hand-written pages
# under docs/labs/{name}/ (like getting-started/) are never touched.
STUB_MARKER = '<meta name="generator" content="pathfinding-cloud-lab-stub">'

# Markers in the template that we replace with per-lab content. The regex
# matches the entire existing block (including the leading comment) so the
# replacement is self-contained and idempotent across re-runs.
TITLE_PATTERN = re.compile(r"<title>[^<]*</title>", re.IGNORECASE)
DESCRIPTION_PATTERN = re.compile(
    r'<meta\s+name="description"\s+content="[^"]*"\s*>', re.IGNORECASE
)
OG_BLOCK_PATTERN = re.compile(
    r'<!--\s*Open Graph[^>]*-->.*?<!--\s*Twitter Card\s*-->.*?<meta\s+name="twitter:image"\s+content="[^"]*"\s*>',
    re.IGNORECASE | re.DOTALL,
)


def truncate(text: str, limit: int) -> str:
    """Trim text to `limit` chars without cutting mid-word, with ellipsis."""
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return cut + "…"


def build_meta_block(lab: dict, slug: str, hero_url: str) -> str:
    title = lab.get("displayName") or lab.get("name") or slug
    description = truncate(lab.get("description") or "", 280)
    page_title = f"{title} - pathfinding.cloud Labs"
    page_url = f"{SITE_BASE_URL}/labs/{slug}/"

    # All values are HTML-attribute-escaped because they originate from
    # lab-author-controlled markdown.
    e = lambda s: escape(s, quote=True)

    return (
        f'<!-- Open Graph / Social Sharing -->\n'
        f'    <meta property="og:type" content="article">\n'
        f'    <meta property="og:url" content="{e(page_url)}">\n'
        f'    <meta property="og:title" content="{e(page_title)}">\n'
        f'    <meta property="og:description" content="{e(description)}">\n'
        f'    <meta property="og:image" content="{e(hero_url)}">\n'
        f'    <!-- Twitter Card -->\n'
        f'    <meta name="twitter:card" content="summary_large_image">\n'
        f'    <meta name="twitter:title" content="{e(page_title)}">\n'
        f'    <meta name="twitter:description" content="{e(description)}">\n'
        f'    <meta name="twitter:image" content="{e(hero_url)}">'
    ), page_title, description


def hero_url_for(slug: str) -> str:
    if (LABS_OUTPUT_DIR / slug / "hero.png").exists():
        return f"{SITE_BASE_URL}/labs/{slug}/hero.png"
    return GENERIC_HERO_URL


def render_stub(template: str, lab: dict, slug: str) -> str:
    hero_url = hero_url_for(slug)
    meta_block, page_title, description = build_meta_block(lab, slug, hero_url)

    # Prepend the generator marker so reconciliation can identify stub-owned
    # dirs and skip hand-written pages.
    meta_block = f"{STUB_MARKER}\n    " + meta_block

    e = lambda s: escape(s, quote=True)

    out = template
    if not OG_BLOCK_PATTERN.search(out):
        raise RuntimeError("Template OG/Twitter block not found -- check docs/labs/index.html structure.")
    out = OG_BLOCK_PATTERN.sub(lambda _m: meta_block, out, count=1)

    if not TITLE_PATTERN.search(out):
        raise RuntimeError("Template <title> not found.")
    out = TITLE_PATTERN.sub(f"<title>{e(page_title)}</title>", out, count=1)

    if not DESCRIPTION_PATTERN.search(out):
        raise RuntimeError("Template <meta name=\"description\"> not found.")
    out = DESCRIPTION_PATTERN.sub(
        f'<meta name="description" content="{e(description)}">', out, count=1
    )

    return out


def listed_slugs() -> set:
    """Slugs that appear in docs/labs.json (the SPA index). Stubs are only
    generated for these — labs absent from the index can't be routed to by
    the SPA, so a stub for them would just route to /labs/ on load."""
    if not LABS_INDEX_PATH.exists():
        return set()
    try:
        index = json.loads(LABS_INDEX_PATH.read_text(encoding="utf-8"))
    except Exception:
        return set()
    return {entry.get("slug") for entry in index if entry.get("slug")}


def main() -> int:
    if not TEMPLATE_PATH.exists():
        print(f"ERROR: template not found: {TEMPLATE_PATH}", file=sys.stderr)
        return 1
    if not LABS_DATA_DIR.exists():
        print(
            f"ERROR: lab data dir not found: {LABS_DATA_DIR}. "
            f"Run scripts/generate-labs-json.py first.",
            file=sys.stderr,
        )
        return 1

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    listed = listed_slugs()
    if not listed:
        print(
            f"ERROR: no slugs found in {LABS_INDEX_PATH}. "
            f"Run scripts/generate-labs-json.py first.",
            file=sys.stderr,
        )
        return 1

    written = 0
    skipped_unlisted = 0
    for json_path in sorted(LABS_DATA_DIR.glob("*.json")):
        slug = json_path.stem
        if slug not in listed:
            # Orphan data file (e.g., from a previous slug naming convention).
            # generate-labs-json.py now reconciles these on each run, but
            # guard here in case stubs are regenerated independently.
            skipped_unlisted += 1
            continue
        try:
            lab = json.loads(json_path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  ! {slug}: failed to parse JSON ({e})", file=sys.stderr)
            continue

        try:
            stub_html = render_stub(template, lab, slug)
        except Exception as e:
            print(f"  ! {slug}: render failed ({e})", file=sys.stderr)
            continue

        stub_dir = LABS_OUTPUT_DIR / slug
        stub_dir.mkdir(parents=True, exist_ok=True)
        (stub_dir / "index.html").write_text(stub_html, encoding="utf-8")
        written += 1

    # Reconcile: delete stub dirs for slugs that are no longer listed.
    # Identify stub-owned dirs by the STUB_MARKER meta tag in their
    # index.html so hand-written pages (e.g. docs/labs/getting-started/) are
    # never touched even if their slug isn't in labs.json.
    removed = 0
    for entry in LABS_OUTPUT_DIR.iterdir():
        if not entry.is_dir():
            continue
        if entry.name in listed:
            continue
        index_html = entry / "index.html"
        if not index_html.exists():
            continue
        try:
            head_text = index_html.read_text(encoding="utf-8", errors="replace")[:4096]
        except Exception:
            continue
        if STUB_MARKER not in head_text:
            continue  # not one of ours
        import shutil
        shutil.rmtree(entry)
        removed += 1

    print(f"Generated {written} lab stubs under {LABS_OUTPUT_DIR.relative_to(REPO_ROOT)}/")
    if skipped_unlisted:
        print(f"  Skipped {skipped_unlisted} unlisted slug(s) (data file present but not in labs.json)")
    if removed:
        print(f"  Removed {removed} orphan stub dir(s) for slugs no longer in labs.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
